/* eslint-disable linebreak-style */
const mongoose = require('mongoose');
const Resource = require('../models/Resource');

const data = [
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  },
  {
    confirmed: false,
    category: 'Accounting',
    type: 'books',
    title: 'ddd',
    link: 'http://dd.com',
    source: 'http://dd.com',
    author: 'ddd',
    level: 'Intermediate',
    avgRating: '4',
    user_id: '5c16e8de76e09e200c039178',
    lastEdited: Date.now()
  }
];

function seedBookResource() {
  data.forEach(function(seed) {
    Resource.create(seed, function(err, subject) {
      if (err) {
        console.log(err);
      } else {
        subject.save();
      }
    });
  });
}

module.exports = seedBookResource;
